import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

// --- Workbox Standard Configuration ---
// Declare self as any to allow Service Worker properties without strict lib checks
declare const self: any;

self.skipWaiting()
clientsClaim()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// --- Push Notification Logic ---

// 1. Listen for Push Event
self.addEventListener('push', (event: any) => {
  if (!event.data) return

  try {
    const data = event.data.json()
    const title = data.title || 'BudgetIA'
    const options = {
      body: data.body || 'Nova notificação',
      icon: data.icon || '/pwa-192x192.png',
      badge: data.badge || '/pwa-192x192.png',
      data: data.url || '/', // Store URL to open
      tag: data.tag || 'general'
    }

    event.waitUntil(
      self.registration.showNotification(title, options)
    )
  } catch (err) {
    console.error('Error handling push event:', err)
  }
})

// 2. Handle Notification Click
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close() // Close the notification

  // Open the app or focus if already open
  const urlToOpen = event.notification.data || '/'

  event.waitUntil(
    self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true
    }).then((clientList: any) => {
      // If a window is already open, focus it
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus()
        }
      }
      // Otherwise open new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen)
      }
    })
  )
})
